services:
  - type: web
    name: minecraft-web-proxy
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
